### ISSUE TITLE
Stage editor content should be full width when the context help is minimized

### ISSUE THREAD

**Issue by jthrilly** [codaco/Architect#101]
Currently when editing a stage the content retains its right margin when the context help is minimized. It should responsively expand to full width.

Ideally, the underlying implementation would be refactored, since the current approach depends on some "tricks" using layers that render on top of each other. Could the guidance component be changed to use context (or even redux) to update the content of the side panel?

**Comment by wwqrd** [comment]
Resolved by https://github.com/codaco/Architect/pull/111
