### ISSUE TITLE
Identify ego in a roster-based study

### ISSUE THREAD

**Issue by berniehogan** [codaco/Architect#126]
If we are doing a roster, we need a way to identify that the respondent is one of the people who are in the roster. 

This might involve selecting ego from a node form (which would be a Network Canvas issue), or somehow putting ego in the name of the file. Ideally, it should be a way that when we export the data from Server where there is a roster we can link these together in a whole network. 

It is an Architect issue since we need to be able to distinguish panels where ego is included from panels where ego is not included. This might involve a specific custom form "The respondent is in the roster" feature that auto-generates a question before the roster that queries for ego, or a skip flow logic that removes ego from a panel based on being nominated on another form.

**Comment by jthrilly** [comment]
We resolved to do this via adding an interface to set an attribute on a roster node, and then manually excluding nodes with that attribute from subsequent alter data capture tasks.
