### ISSUE TITLE
Information Interface needs `title` field

### ISSUE THREAD

**Issue by bryfox** [codaco/Architect#143]
The stage editor UI displays "title" for each interface type, but this is translated to "label" in the protocol's stage data.

The Information Interface has an additional "title" prop (required in theory), which displays, for example, "Welcome to the Teaching Protocol".

**Comment by wwqrd** [comment]
The Title section is all interfaces in Architect and refers to the label property which is used for the sidebars in Network Canvas. Perhaps it could do with renaming or additional explanation?

You can create a title that would be visible on the interface using the text content type?

**Comment by bryfox** [comment]
I can create multiple text items, but [in addition to items](https://github.com/codaco/Network-Canvas/blob/master/src/containers/Interfaces/Information.js#L50), `<Information>` is designed to read a [title](https://github.com/codaco/Network-Canvas/wiki/Information-Interface#interface-specific-api) from the stage, which gets different styling.

Title/label isn't confusing right now, but I mentioned it since I thought it might get confusing if we needed to add that additional "title" to the Information editor.

**Comment by jthrilly** [comment]
Good spot, Bryan.

**Comment by wwqrd** [comment]
I see now!

I'll rename the shared "title" component to "label", and create a title component for the Information interface.
