### ISSUE TITLE
Implement Automatic Update/Upgrade

### ISSUE THREAD

**Issue by jthrilly** [codaco/Architect#146]
Architect should implement the system used by NC whereby the user is able to check for updates to the app, and install them.

**Comment by wwqrd** [comment]
@jthrilly Notice some feedback on the Server implementation, are you okay with this from a UI perspective (using electron's dialog), if so, the example implementation looks pretty good:

- This shows adding a "check for updates", option in the menu
- Easy enough to run "check for updates" on start

Either will result in a dialog giving the user an opportunity to download the update or ignore it.

Rough implementation here: https://github.com/codaco/Architect/tree/feature/auto-update

**Comment by jthrilly** [comment]
I'd prefer if we were able to keep the update process somewhat consistent, at least between the two desktop apps. Since @bryfox will be implementing this in Server, do you want to wait and just bring those changes over (as best you can) when that is finished?
