### ISSUE TITLE
Constrain size of media on information interface

### ISSUE THREAD

**Issue by jthrilly** [codaco/Architect#147]
On the information interface, the size of images should be constrained so that they do not push other content off of the screen.

The size of the content box should be proportional to the total number of content boxes. This will be tricky, and might require setting a max height for other items, such as text boxes, and associated word/character limit.

**Comment by wwqrd** [comment]
Size of content should be constrained on Network canvas so as not to cause scrolling.

Based on discussion we decided that the simplest way to conceptualise this to users is to have a grid-like quota:

![sizes](https://user-images.githubusercontent.com/776599/45295499-d8612600-b4f6-11e8-92fe-3b386956b62e.png)

Which could then be combined for an interface:

![combined](https://user-images.githubusercontent.com/776599/45295500-d9925300-b4f6-11e8-807a-285cfb220804.png)

This will require changes to the UI of architect, and the protocol format/Network Canvas

**Comment by wwqrd** [comment]
closed by https://github.com/codaco/Architect/pull/238 & https://github.com/codaco/Network-Canvas/pull/685
