### ISSUE TITLE
improve file loading back-end flow

### ISSUE THREAD

**Issue by wwqrd** [codaco/Architect#162]
File loading is now triggered by the route, which can lead to some strange edge cases when:

- App data is reset whilst at a protocol route e.g. `/edit/my-protocol.netcanvas`
- A non-existent file is specified e.g. `/edit/not-a-real-file.netcanvas`

Whilst these are unlikely real-world issues, they highlight an underlying fragility in the way these files are loaded. There are no error cases for example.

This issue is a space for planning what these new redux events / actions might look like.

Outline:

## modules:

```
state: {
 recentProtocols, // List of paths to recent protocols
 protocols, // Protocols that have been opened this session
 protocol, // Current protocol
}
```

#### recentProtocols

List of protocols in user paths (e.g. `/Users/JamesBond/Desktop/myprotocol.netcanvas`. May also contain meta data, like last edited date.

#### protocols 

Internal meta data about protocols, where the working copy exists in tmp, user path, whether or not it's an advanced protocol.

#### protocol

Currently loaded protocol, i.e. contents of `protocol.json`

## routes

`/edit/{protocolId}` // refers to id in `protocols` module

## opening a protocol

1. `IMPORT_PROTOCOL` { path }
  a. extract to /tmp/ (bundled)
  b. copy to /tmp/ (unbundled, advanced)
1. Either:
  a. `IMPORT_PROTOCOL_SUCCESS` { importedPathName }
  b. `IMPORT_PROTOCOL_ERROR` { path }
1. On success, save meta to `protocols`
1. `LOAD_PROTOCOL` { id }
1. Either:
  a. `LOAD_PROTOCOL_SUCCESS` { id, fileData }
  b. `LOAD_PROTOCOL_ERROR` { id, fileData }
1. On success, save meta to `recentProtocols`

## saving a protocol

1. `SAVE_PROTOCOL` // derived from active protocol
  a. write to /tmp dir
1. Either:
  a. `SAVE_PROTOCOL_SUCCESS`
  b. `SAVE_PROTOCOL_ERROR`
1. `EXPORT_PROTOCOL` // derived from active protocol
  a. compress, write to user path (bundled)
  b. copy, write to user path (unbundled, advanced)
1. Either:
  a. `EXPORT_PROTOCOL_SUCCESS` { id }
  b. `EXPORT_PROTOCOL_ERROR` { id }
1. On success, save meta to `recentProtocols`

**Comment by jthrilly** [comment]
"Advanced" is where you open an unbundled protocol.js, right?

**Comment by wwqrd** [comment]
Yes that's right, I've updated the description

**Comment by wwqrd** [comment]
This has already been implemented.
