### ISSUE TITLE
User may open multiple windows

### ISSUE THREAD

**Issue by bryfox** [codaco/Architect#164]
I'm not sure if you'd consider this an issue in Architect or not, but I did on Server.

A user may spawn new windows by cmd- or shift-clicking:
![multiple-windows](https://user-images.githubusercontent.com/39674/43600692-4db90fc4-9659-11e8-909a-e0584e0c6013.png)

[I handled this in Server with the `new-window` event](https://github.com/codaco/Server/blob/3a5015a9/src/main/components/mainWindow.js#L73-L77).

**Comment by wwqrd** [comment]
Sneaky! Somewhat related to #65

**Comment by wwqrd** [comment]
@bryfox I can't replicate this, can you please give exact steps?

**Comment by bryfox** [comment]
In the screenshot above, I cmd-clicked (macOS) the person node in the background window. I think shift-click is the equivalent on Windows.

Anything that links to a new path should have this behavior.

**Comment by wwqrd** [comment]
I decided to go with preventing the action completely -- otherwise it causes a full app reload. The user can then click again without the shortcut key.
