### ISSUE TITLE
Cannot save protocol after edits to form

### ISSUE THREAD

**Issue by bryfox** [codaco/Architect#167]
If I edit or delete a form from the "Manage Forms" screen, then I'm not prompted to save my protocol on the main screen, and any changes I made are lost upon reload.

Example Steps:
1. Create a new protocol
2. Click Manage Forms
3. Create & save a new form (using person node)
4. Edit that form
5. Give it a new Title, and click save

Changes appear to save, but there is no "Save" back on the main protocol screen.

**Comment by bryfox** [comment]
Side note: the reason I wanted to change my form name was to be able to use the [default form](https://github.com/codaco/Network-Canvas/wiki/protocol.json#forms) for a new node type. I created a `venue` node, and initially called the form "New Venue Form".

Having now gone through it, supporting that default behavior may be more confusing than it's worth, but if we're keeping it, then the guidance text should probably be updated.

**Comment by bryfox** [comment]
Another note, in case it helps track down the problem: in my created protocol, I see an empty `"name"` field, when I think the venue name is actually the key?

Excerpt:

```json
    "VenueForm": {
      "name": "",
      "title": "Venue Form"
```

**Comment by wwqrd** [comment]
I'd also like to make the button names part of this issue.

'Save' from one of the edit views doesn't save to disk, I think a better label would be 'continue'.

So the two options on edit views would be:
[Continue] [Cancel]
