### ISSUE TITLE
Ordering of node bucket on Network Canvas ignores rules set in Architect

### ISSUE THREAD

**Issue by wwqrd** [codaco/Architect#170]
Could be an issue with how they are generated in Architect, or read in Network Canvas

Age descending:
<img width="1152" alt="screen shot 2018-08-06 at 15 53 08" src="https://user-images.githubusercontent.com/776599/43727468-fa3e57ca-9999-11e8-8218-7a771d005b08.png">

**Comment by wwqrd** [comment]
[Test.netcanvas.zip](https://github.com/codaco/Architect/files/2263284/Test.netcanvas.zip)

**Comment by wwqrd** [comment]
[Test.netcanvas.zip](https://github.com/codaco/Architect/files/2263291/Test.netcanvas.zip)

**Comment by bryfox** [comment]
Should "sortOrderBy" contain "property" instead of "variable"?
