### ISSUE TITLE
additional attributes hard to read

### ISSUE THREAD

**Issue by rebeccamadsen** [codaco/Architect#173]
On the name generator screen, additional attributes title is hard to read. In Name generator, click on a prompt, and edit additional attributes.

![edit variable](https://user-images.githubusercontent.com/16093053/43729526-88a42e1e-9976-11e8-8e93-fbf68f4e58da.png)

**Comment by jthrilly** [comment]
Just to note that the background color of this panel was fixed in https://github.com/codaco/Architect/pull/188

The issue remaining is that the input label is white, whereas it should use the css text color var here.
