### ISSUE TITLE
When creating a form from Name Generator, it might make sense to "lock" the form editor to same type

### ISSUE THREAD

**Issue by wwqrd** [codaco/Architect#180]
For example if the name generator was for a 'person' node, you might create a form for a 'place' node. 

This means that we can't use the new form in the name generator and so the form value in Name Generator is not set.

It might make sense to "lock" the form editor to same type as the NameGenerator

**Comment by jthrilly** [comment]
I'd file this under nice, but not essential.

**Comment by jthrilly** [comment]
This is now obsolete.
