### ISSUE TITLE
Changes to protocol renaming

### ISSUE THREAD

**Issue by jthrilly** [codaco/Architect#185]
In accordance with the discussion in #156, we want to change the way the protocol renaming happens:

- Remove the ability to rename a protocol from the overview card (should happen in #184)
- Add a new menu item ("Rename Protocol").
- Clicking this item triggers a new flow, whereby:
  - The user is prompted for a new protocol name, AND
  - The user is prompted to save the new protocol in a new location

This effectively forces the user to "fork" the existing protocol.

**Comment by rebeccamadsen** [comment]
Is this satisfied by this: https://github.com/codaco/Architect/pull/496?

**Comment by jthrilly** [comment]
Yep!
