### ISSUE TITLE
Variable chooser is bugged

### ISSUE THREAD

**Issue by jthrilly** [codaco/Architect#190]
The variable chooser for prompt variables seems to not behave correctly. 

- Boolean variables show '0' and '1' as potential values, rather than true/false.
- The input label is white, which looks bad on the light gray background.
- The button label should only change to "Done" when a value has been selected/changed. Perhaps simpler to just show a cancel button at all times, which would remove the need for this logic.

**Comment by wwqrd** [comment]
This isn't a fully implemented feature, not a bug as such.

**Comment by wwqrd** [comment]
#173 is related
