### ISSUE TITLE
Skip logic builder 2.0

### ISSUE THREAD

**Issue by jthrilly** [codaco/Architect#194]
Currently node or edge queries constructed using the skip logic query builder require a variable. We would like to change this behavior to allow EITHER a variable comparison, OR a straight check for the node or edge type.

For example, it is not possible to construct a query that simply states "edge of type X exists". Currently, we must select the edge type and select a variable, before defining the logical comparison.

## Desired possible rules:

entity_type -> variable -> logical_comparison
entity_type -> logical_comparison

## Logical comparisons

Logical comparisons for straight node or edge queries can realistically be limited to "exists" || "not exists". 

Other discussion: https://github.com/codaco/Architect/pull/193

**Comment by rebeccamadsen** [comment]
`networkQuery` uses `id` in places, but NC uses `_uid` now. I think this will affect the edge rules mostly, but edge matching rules will not work as expected in NC until we update `networkQuery` to look at `_uid`s.
