### ISSUE TITLE
Support duplicate color definitions

### ISSUE THREAD

**Issue by bryfox** [codaco/Architect#225]
NC-UI defines two [duplicate edge colors](https://github.com/codaco/Network-Canvas-UI/blob/master/styles/global/_default.scss#L104-L110):

```
@include palette-set('edge-color-seq-3', color('neon-coral'));
@include palette-set('edge-color-seq-9', color('neon-coral'));
```

I'm not sure if that's intentional, but it causes duplicate component instances for edge color swatches. Should Architect use something other than color values as keys to be safe?

![edit-edge](https://user-images.githubusercontent.com/39674/45381562-9c4fc300-b5d3-11e8-82de-9d2f0a9ef272.png)

**Comment by wwqrd** [comment]
We've updated the palette not to clash (they are intended to be unique colors), so this issue has gone for now.

The color picker is a component from a library (where the key is declared). Should this issue come up again, we can build our own component to replace it.
