### ISSUE TITLE
12 character limit for stage names is too short?

### ISSUE THREAD

**Issue by wwqrd** [codaco/Architect#228]
"WWWWWWWWWWWW" is a good example for the maximum space this takes up on the navigation bar. "Sociogram do" illustrates limitations for 2 word names.

<img width="411" alt="screen shot 2018-09-12 at 13 09 41" src="https://user-images.githubusercontent.com/776599/45424031-2445d380-b68d-11e8-8d78-5b9ee9cf929c.png">

**Comment by jthrilly** [comment]
This UI will be changed as part of part three of the the new menu system in NC, so yes I think we can definitely increase this. Probably something like 25 chars?
