### ISSUE TITLE
In use edges/nodes can be deleted, breaking related interfaces

### ISSUE THREAD

**Issue by wwqrd** [codaco/Architect#232]
It is possible to delete edges and nodes that are in use, which produces invalid interfaces (https://github.com/codaco/Network-Canvas/issues/673, https://github.com/codaco/Network-Canvas/issues/674).

Some possible solutions:
- Allow deletion, but mark protocol as invalid and prevent saving until it's fixed.
- Prevent deletion until related interfaces are changed.

**Comment by jthrilly** [comment]
Third option:

- Delete any interfaces, forms (prompts? others?) that are configured using this node or edge type, thereby maintaining a valid protocol.

**Comment by wwqrd** [comment]
> Delete any interfaces, forms (prompts? others?) that are configured using this node or edge type, thereby maintaining a valid protocol.

I like this option, presumably if they are deleting the node/edge, the interfaces are no longer relevant.

If the do want to migrate any stages this would still be possible if they were changed first.

- When deleting a type notify user of the implications (and specify where it's being used)
- Delete any associated stages/forms.

Bonus:

- Add information to node/edges registry indicating where assets are used
