### ISSUE TITLE
Flag unused variables / forms in registry editor

### ISSUE THREAD

**Issue by wwqrd** [codaco/Architect#237]
https://github.com/codaco/Architect/issues/163#issuecomment-410641096

> Another point on this: we intend to have some sort of functionality to let people find unused variables, assets, and other stuff.

where are variables used (not extensive):

  - forms
  - filter rules
  - prompt.additionalAttributes
  - cardOptions.additionalProperties
  - cardOptions.sortableProperties

**Comment by jthrilly** [comment]
This is heavily impacted by changes to the design of the "variable registry" (https://github.com/codaco/Architect/issues/394)
