### ISSUE TITLE
'highlight' configuration values missing

### ISSUE THREAD

**Issue by bryfox** [codaco/Architect#253]
On the [sociogram](https://github.com/codaco/Network-Canvas/wiki/Sociogram#example-configuration), Network Canvas will look for a highlight property and set the [`variable` to its `value`](https://github.com/codaco/Network-Canvas/blob/v4.0.0-alpha.7/src/selectors/sociogram.js#L63).

Architect doesn't set `value`, so attributes won't be toggled.

- Architect should allow `value` configuration
- Architect needs to also allow configuring the `value` type (or document otherwise)?
- Should Architect default value to true?
- Should Network Canvas infer an undefined `value` to be truthy (since `undefined` results in a no-op)?

**Comment by wwqrd** [comment]
We did decide to only allow boolean variables here, which are only ever going to have a value of true. Making the value config is redundant. So perhaps we should remove it outright.

However, if we want to keep the flexibility of having a `value` prop, my feeling is that we shouldn't default in NC, as the variable type could be non-boolean.

**Comment by wwqrd** [comment]
Superseded by https://github.com/codaco/Network-Canvas/issues/710
