### ISSUE TITLE
Node/edge label vs. name

### ISSUE THREAD

**Issue by wwqrd** [codaco/Architect#259]
Node/edge types are defined in the variable registry with UUIDs, and a `label` property e.g.:

<img width="330" alt="screen shot 2018-10-10 at 16 13 39" src="https://user-images.githubusercontent.com/776599/46746687-79363300-cca7-11e8-87ab-294386c0cc39.png">

Variables are defined with UUIDs and a `name` property for export, and `label` for display e.g.:

<img width="349" alt="screen shot 2018-10-10 at 16 14 16" src="https://user-images.githubusercontent.com/776599/46746776-ae428580-cca7-11e8-9116-d4b6a8c208f8.png">

Node edge types should also include a "name", or alternatively we could remove "label" from both, and use "name" for display and export.

**Comment by wwqrd** [comment]
Actually this is a non-issue, on further inspection:

> When we create a type we give it a “name” property which is just a clone of label, and we don’t allow the user to change it (I thought it wasn’t getting a name in the first place).
>
> With variables, we allow the user to customise the name at will.
>
> It’s a disparity, but doesn’t necessarily need to change.

**Comment by wwqrd** [comment]
Actually it is indeed missing the name property, will add this as a new field, auto populated from label.

**Comment by rebeccamadsen** [comment]
Wasn't this resolved in #259, or did I miss something?

**Comment by wwqrd** [comment]
Yes I think so 👍
