### ISSUE TITLE
Boolean additionalAttributes should default to true

### ISSUE THREAD

**Issue by bryfox** [codaco/Architect#264]
When I add a boolean additionalAttribute (like "close friend"), it has an undefined value. In order to have it save as `false`, I need to toggle it on then off again, but there's no indication that this is required, or that the initial undefined state is different than `false`.

**Comment by jthrilly** [comment]
I've noticed this, too. However I think it should default to `true` given the context.

**Comment by jthrilly** [comment]
@wwqrd - just wanted to confirm that this was fixed in #284 (please close if it was).

**Comment by wwqrd** [comment]
Yep this is fixed, boolean attributes default to true.
