### ISSUE TITLE
sociogram scrolling to top

### ISSUE THREAD

**Issue by rebeccamadsen** [codaco/Architect#270]
Whenever I click on a checkbox in sociogram, it scrolls to the top. It's a little distracting to have to scroll back down.

**Comment by wwqrd** [comment]
Seems to be affected by the position of the open close menu button?

Okay:
<img width="728" alt="screen shot 2018-10-15 at 12 37 40" src="https://user-images.githubusercontent.com/776599/46948811-2bd70e80-d077-11e8-928a-1f62952a44b6.png">

Not okay:
<img width="726" alt="screen shot 2018-10-15 at 12 37 22" src="https://user-images.githubusercontent.com/776599/46948824-3beeee00-d077-11e8-9176-44dda781213b.png">
