### ISSUE TITLE
Asset management workflow

### ISSUE THREAD

**Issue by jthrilly** [codaco/Architect#290]
## Background

This feature covers what had previously been described as two concepts, but that we now wish to revise into one:
- assets - imported on the information interface, and exist solely as files in the `assets/` directory. 
- external data - a network object (`{ nodes, edges } `) stored in the protocol file, used on the name generator and the roster interfaces.

The key changes we want to make are:
- Assets are also indexed in an `assetManifest` on the protocol.
- External data will not be part of the protocol file, and will instead be imported as files (assets) - therefore these will also be added to the `assetManifest`.
- Long term, we will also be adding async data sources. These will also be part of the asset manifest.

## Tasks

To facilitate these changes we will:

1. Rename references `externalData` to `assetManifest`, and make any other necessary changes to the protocol format. (#363)
2. Create a network data upload component, and ensure uploads are added to the assetManifest (#364)
3. Create an inline asset browser, so a user can choose between uploading a file and selecting one from the manifest. (#365)
5. Build the asset manager view, which will allow users to review/edit assets protocol wide. (#366)

**Comment by wwqrd** [comment]
Does anything new need adding to this, or is it still done?
