### ISSUE TITLE
Should display reason when protocol is dirty but cannot be saved?

### ISSUE THREAD

**Issue by bryfox** [codaco/Architect#297]
We don't allow saving of an invalid protocol (e.g., #233); the save button may be disabled with no indication of why.

Steps:
- Create a new protocol
- Create new entities, forms, etc.
- Attempt to save my in-progress edits

If a user cannot save in-progress editing [which would result in an invalid protocol], should we have some indication of what they need to do to proceed?

**Comment by jthrilly** [comment]
We have largely addressed this, so closing for now.
