### ISSUE TITLE
Form variables should occur only once

### ISSUE THREAD

**Issue by bryfox** [codaco/Architect#298]
Currently, I can add the same variable to a form multiple times (and all render in NC):

<img width="763" alt="form-vars" src="https://user-images.githubusercontent.com/39674/47679684-375c2680-db9b-11e8-837d-c5b863d2b966.png">

**Comment by jthrilly** [comment]
This is still valid as of Beta 1. Question is, should we just leave this to the researcher? Seems like more trouble that it would be worth to address.
