### ISSUE TITLE
Ability to sort and filter variables

### ISSUE THREAD

**Issue by jthrilly** [codaco/Architect#301]
With a long list of variables, it becomes tedious to scroll through the list in the variable  registry.

I propose that we allow filtering (matching on variable name and variable type), and sorting (variable name, and type). It might also be good to have some sort of color accenting for variables to indicate their type. Take inspiration from the new menu UI in NC.

**Comment by wwqrd** [comment]
Is there going to be a similar issue here?: https://github.com/codaco/Architect/issues/294

**Comment by jthrilly** [comment]
Possibly! Although I like the UI for the additional attributes chooser, perhaps creating a reusable list component, with overflow scroll styling and configurable filter components (à-la `<NodeList>`/`<CardList>` in NC) would be good.

**Comment by wwqrd** [comment]
Sorry that wasn't clear: Do we want to add some kind of filtering sorting to attributes table too?

**Comment by jthrilly** [comment]
Yeah, I realised but didn't communicate clearly. Sorry! I was saying that I like how it works with the attributes table now. I was trying to suggest that a reusable list component (which renders arbitrary items, like the one in NC) would cover both use cases.
