### ISSUE TITLE
Errors during protocol opening should provide user feedback

### ISSUE THREAD

**Issue by bryfox** [codaco/Architect#304]
If an error is thrown while trying to open a protocol, the operation fails silently. An error message should be presented to the user.

Examples:
- open an protocol with invalid JSON, or a corrupted file
- open a file from the recent_protocols list which no longer exists at that location on disk

In the latter case, should we also allow the user to delete the item or locate it on disk?

**Comment by bryfox** [comment]
> open a file from the recent_protocols list which no longer exists at that location on disk

Related: the 'recent protocols' list now shows protocols which may never have been saved, since the file isn't written until after the first changes are made.

Should 'recent protocols' only display protocols which have been saved at least once? Should the protocol scene's home button warn about unsaved changes (before navigating away) when the only change is having named the file?

**Comment by rebeccamadsen** [comment]
One place I've noticed this is when I "Create New", but don't save the file. Is it possible to move the "Save As..." dialog as part of the "Save" button within the protocol? We already don't create the file until it's a valid protocol for saving, but maybe the user shouldn't have to think up a name for the file either until it's time to save?

Of course, it's still possible for the user to move/delete/rename an existing protocol so it doesn't completely solve this issue of telling the user when there's an error in opening a protocol.
