### ISSUE TITLE
Consider disallowing opening a protocol with no name

### ISSUE THREAD

**Issue by bryfox** [codaco/Architect#305]
The `name` property in a protocol definition is required, as it's the unique identifier for the protocol.

Architect allows me to open an existing protocol without a `name`. This protocol (with any changes) won't be importable into Server, nor (once schema validation is enforced) into NC.

Theoretically, a user could make edits and later "fork" the protocol to rename it (#185), but it might be clearer to display an error up front instead.

**Comment by jthrilly** [comment]
Would running schema validation of the protocol on open in Architect fix this?

**Comment by bryfox** [comment]
Yes, but is that desired? Architect does an increasingly good job of highlighting errors and allowing a user to fix them, so I don't know that we'd want to prevent all invalid protocols from opening. `name` is special in that it's immutable.

**Comment by wwqrd** [comment]
Since this should only happen in the case that someone custom built a protocol, I think it's reasonable to refuse to open it. Maybe we could have a 'light' version of the schema validation purpose built for this.

**Comment by jthrilly** [comment]
> Since this should only happen in the case that someone custom built a protocol, I think it's reasonable to refuse to open it.

Completely agree. It seems logical:

- Architect can only create valid protocols
- Architect can only open valid protocols

Any error outside of Architect is the responsibility of the user.

**Comment by bryfox** [comment]
I opened #307 to cover "Architect can only create valid protocols".

For "Architect can only open valid protocols", we probably need to have a versioning discussion sooner than later.

**Comment by bryfox** [comment]
When we say 'protocol version' are we talking about the `networkCanvasVersion` field? Seems fine. It probably doesn't matter until we try to deal with interop/compatibility, though; right now it's not used as far as I know.

**Comment by jthrilly** [comment]
Correct. My suggestion would be to have a schema version that corresponds to the release version of the apps that validate and work with that schema.

For now it would be a soft enforcement for opening a protocol. So perhaps a dialog ("This protocol was created in an earlier||later version of Architect, and may not function correctly with this version. During the Alpha phase, protocol version interoperability is not guaranteed. During the Beta period, we will support migrating your protocol. Please contact us with any questions you have, or problems that you encounter.").

Once the above dialog is acknowledged, the protocol will open as normal. Saving the protocol subsequently should update the schema version. 

If we continue to use semver for both app and schema versions, we should be able to easily check if a given protocol schema version is compatible with a given app. We can even provide ranges.

We can then also provide "automatic" conversion (in Architect) to newer protocol formats in the future (should we wish).

**Comment by bryfox** [comment]
To recap, there are 3 things we're versioning:

- the protocol (`networkCanvasVersion`)
- the app (x3)
- the schema (+ data/business logic)

I think we're saying that `networkCanvasVersion` really represents which version of the [Architect] app created it, so it makes sense to match app version and networkCanvasVersion.

> check if a given protocol schema version is compatible with a given app

This suggests that schema and app versions should be decoupled, which I agree with. I think it's clearer to *not* match the app and schema versions, partly for this reason. An app version may support multiple schema versions, and a new app release may not have any schema changes at all.

If the protocol networkCanvasVersion matches the app version (as above), this wouldn't give Architect a way to unambiguously tell NC which schema to validate with, but that seems OK to me.

> soft enforcement for opening a protocol

Originally, I assumed that validation itself would play this role. Would this be in addition to validation (e.g., only displaying the dialog if validation fails)? Or do we want to rely solely on this versioning at runtime and use schemas only as development-time assertions?

That question aside, I like this; seems like it makes migrations more explicit.

**Comment by jthrilly** [comment]
Versioning and naming has changed dramatically since this issue was created, so closing.
