### ISSUE TITLE
Template must be a valid protocol

### ISSUE THREAD

**Issue by bryfox** [codaco/Architect#307]
From #305: Architect can only create valid protocols.

Currently, Architect initially creates an invalid protocol, since we require one or more stages to be defined.

**Comment by wwqrd** [comment]
Not sure how to go about this? We could automatically add a stage, but why would the user want that?

**Comment by jthrilly** [comment]
We handle this at the "create" step - the user cannot save a protocol that is invalid. Is that possible?

**Comment by rebeccamadsen** [comment]
Maybe we should wait to prompt the user for a protocol name until they first "save", so until then it's a "temp" protocol. That way they only ever save a valid protocol.

**Comment by wwqrd** [comment]
I've been thinking about this the wrong way.

The current limitation is that the create button creates a protocol then automatically opens it for editing. But that's self imposed. A better workflow would be to work on a "temp" protocol until you first save it like you say @rebeccamadsen.
