### ISSUE TITLE
Color picker doesn't show any colors

### ISSUE THREAD

**Issue by wwqrd** [codaco/Architect#311]
Think this might be related to changes in UI:

<img width="274" alt="screenshot 2018-11-13 at 17 10 24" src="https://user-images.githubusercontent.com/776599/48430421-32849e80-e767-11e8-9561-5c579e43fb19.png">

Related #225

**Comment by jthrilly** [comment]
I removed the duplicate color in my mega-mess PR in a UI commit. Perhaps somehow architect and UI are out of sync?
