### ISSUE TITLE
cannot change drop down values

### ISSUE THREAD

**Issue by rebeccamadsen** [codaco/Architect#334]
Cannot change the value using these drop downs:

![forms](https://user-images.githubusercontent.com/16093053/48726124-685cd380-ebfc-11e8-86f9-717040d99f90.png)

I see this on Windows, with the variable and input type in forms, and variable types when editing nodes, and layout variables on Sociogram. Edge types on Sociogram work fine though.

Also, if you scroll when a dropdown is open, the dropdown disconnects from the input box:

![disconnect](https://user-images.githubusercontent.com/16093053/48726931-cb4f6a00-ebfe-11e8-9a25-368a84880bc4.png)

**Comment by jthrilly** [comment]
Steve and I have both been unable to reproduce the first issue on Windows 10 VMs. I think given the circumstances we are going to have to treat this as a known issue, and release anyway pending further investigation. Please keep looking into it. Steve suggested trying keyboard input, as this seems to also work for us.

The second issue is (I think) somewhat unavoidable with the approach that react-select takes. There are a few issues with users requesting a feature to fix it, but no official one as far as I can see. One simple (but potentially perilous) option would be to set overflow:hidden on the body once a dropdown is open. Maybe worth a try.
