### ISSUE TITLE
Sociogram Prompts contain defunct onBlur properties on Select

### ISSUE THREAD

**Issue by wwqrd** [codaco/Architect#337]
The `onBlur` properties in SociogramPrompt relate the the previous browser input based select component and may be defunct.

Edge creation and attribute toggling are also no longer exclusive, which may relate to new select components.

Additionally the onBlur handler defined in `components/Fields/Select` looks like it may reset a field on blur.

**Comment by wwqrd** [comment]
Prior to react-select, onBlur looked like this:

```
handleBlur = (e) => {
  this.setState({ visited: true });

  if (this.props.input.onBlur) {
    this.props.input.onBlur(e);
  }
}
```

so the `disableBlur` property in the sociogram prompts was probably used to disable the visited state.

**Comment by jthrilly** [comment]
Looks to be resolved?
