### ISSUE TITLE
Static images not showing up in build

### ISSUE THREAD

**Issue by wwqrd** [codaco/Architect#34]
Steps to reproduce:
1. Build and run: `npm run build && npm run electron`
1. Open a protocol
1. Click to add a stage, images don't load.

Images are in `public/images` and are copied over to `www/images`.

**Comment by jthrilly** [comment]
So there are a couple of ways of solving this:

1) The create react app standard way
The CRA and React authors want you to use images like any other bundle-able resource, and use `import` statements to access them. This will then trigger webpack, which will handle things like rewriting the URL, and creating a hash for versions.

`import Image from './img.png'`

2) The public folder method
If we want to keep our images in our `public` folder (which of course becomes our `www` folder), we [need to get the relative path and inject it](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#using-the-public-folder), like this:

``` JSX
// NewStage.js: 70
<img alt="" src={`${process.env.PUBLIC_URL}/images/timeline/stage--${type}.png`} />
```

Given our use-case, and the fact we don't need to use webpack to process these images, I think we should use the second approach.

**Comment by wwqrd** [comment]
Resolved in
