### ISSUE TITLE
"Portalling" to allow creating entities out of context

### ISSUE THREAD

**Issue by jthrilly** [codaco/Architect#360]
There are a number of places within architect where we want to jump to other parts of the protocol within a modal dialog, in order to avoid the user having to navigate away from their current task in order to achieve their objective.

These use-cases mainly revolve around variable creation when editing/creating a stage.

To resolve this, we need to create a system to allow us to "portal" entity creation functionality inside of a modal dialog, which can then take place within the current task flow.

Areas where this needs to be implemented (create sub issues if desired):

- [x] "Additional attributes" within name generator prompt creation - allow creating new variable. (would resolve #293)
- [x] any time an asset is used (picture for sociogram background, data source for roster interfaces and name generator panel) the user should be able to choose from an existing asset, or add a new one.
- [x] variable choosers on the sociogram prompt should have a button that allows the creation of a new variable for the selected node type

For discussion:
- Should node and edge type creation also be possible? For example, should "add new" be an option when selecting a node type? This would probably work best in something other than a modal overlay, such as appearing as an additional "layer" on top of the previous content, where cancelling/okaying this layer will return the user to where they were. We discussed this layering idea some time ago, along with the notion of a slight offset to create a stacked effect. Perhaps we could revive that?

**Comment by jthrilly** [comment]
@wwqrd - when you get a minute, let's chat about this.

**Comment by wwqrd** [comment]
My initial thoughts on this are to move away from using the route to determine UI state and instead only use it for selecting loading protocols. If the UI state is managed by redux, then redux persist should do a good job of keeping us in the same place during development. This should make it much easier to "stack" views, since that can more easily be described in an object than a url string!

**Comment by jthrilly** [comment]
I think that might be overkill. We can create modals that contain any components we want, including views that are currently rendered in response to route. Maybe we can do a call about this? 

Just FYI this is quite a high priority feature, so we should make a plan to finish it pre April.

**Comment by wwqrd** [comment]
I think we can consider this done, we have different varieties of this workflow in place. This issue doesn't name any specific features that aren't already implemented in some sense.
