### ISSUE TITLE
New preview mode implementation

### ISSUE THREAD

**Issue by wwqrd** [codaco/Architect#361]
There are a number of drawbacks (listed below) with the current preview implementation, which uses Network Canvas as a React component within Architect.

We want to try another approach: building Network Canvas as a separate bundle within Architect.

These two approaches both have existing write-ups , though they aren't especially clearly written.

https://github.com/codaco/Architect/issues/4#issuecomment-428155715:
- "Embed app in Architect (inline)" which corresponds to the current approach
- "Embed app in Architect (new window)", which corresponds to the proposed approach.

### Issues with current approach

- The Architect app is run with access to the node environment, but has stricter CSP settings than Network Canvas for security reasons. In the current approach, we would need to add unsafe-eval to the CSP settings to Architect.
- Any CSS variables that have been configured in Architect then need to be set back to the original values in the preview window. As more variables are changed, more exceptions need to be added to the preview.
- We override CSS properties that would otherwise cause NC to inherit incorrect values from Architect using the `.network-canvas` selector for increased specificity, but this does not work for properties that are defined at `<body>` or `<html>` level.  
- Any structural changes in the Network Canvas state will break the way data is side-loaded in the preview.

### Outline of new approach

- Network Canvas is built as a separate bundle within Architect.
- Network Canvas is still a submodule in the Architect source (though outside `/src`), therefore we can easily control version matching
- Network Canvas is run from within the Architect application as a separate BrowserWindow, so we should still see the same instant performance we have currently.
- It's behaviour is exactly that of Network Canvas proper, there is no wrapping of components or need to alter any css.
- Network Canvas will be modified to enable remote control via WebSockets or IPC. This means building functionality into NC which may not be used in the standalone application. The benefit of that is that any issues that arise out of structural changes to NC state will be captured at the time of change (via tests in NC).
- A new npm task for architect that: 1) runs `npm install` for network canvas, 2) runs `npm run build:electron`, 3) copies from NC's www to the preview library location. This will allow us to reuse the existing NC web pack configuration.

**Comment by jthrilly** [comment]
An additional requirement for the new preview mode is that it support generation of mock data. This is particularly needed for interfaces that assume nodes are already present in the interview (sociogram, ordinal bin, etc.).
