### ISSUE TITLE
Create an inline asset browser

### ISSUE THREAD

**Issue by wwqrd** [codaco/Architect#365]
The upload field should be updated to contain a 'browse' link, which will let the user choose from existing files in the assetManifest:
<img width="1000" alt="screenshot 2019-01-08 at 11 49 29" src="https://user-images.githubusercontent.com/776599/50829362-2fa7c380-133c-11e9-950e-07dead7fc8e4.png">

Clicking browse should open a modal with a list of suitable assets from the assetManifest. Selecting one will close the window and set it as the asset for this field.

Part of #290

**Comment by jthrilly** [comment]
Just to add that there are other changes to this panel in #358. Unrelated to the content browser, though.
