### ISSUE TITLE
Rename "additional attributes" to "Assign attributes"

### ISSUE THREAD

**Issue by jthrilly** [codaco/Architect#387]
The additional attributes section of the prompt on the name generator should be renamed to "assign attributes", and include some short text on its purpose.

This is a UI change, not a protocol change (so `additionalAttributes`) can be retained in the protocol file. 

This will resolve #359

**Comment by wwqrd** [comment]
This is partially completed with the new "assign attributes" component, which corrects titles, no helper text has been added.

**Comment by jthrilly** [comment]
I added helper text in: https://github.com/codaco/Architect/pull/480
