### ISSUE TITLE
"Preview" Mode

### ISSUE THREAD

**Issue by jthrilly** [codaco/Architect#4]
This feature would let the user "test" their protocol in Network Canvas, somehow.

**Comment by jthrilly** [comment]
Two possible solutions:
- Launch NC via command line argument, or by dragging a file into NC (electron drag and drop is implemented in Server). Needs corresponding issue in NC.
  - PRO: allows using system installed NC version. This means NC version can be updated.
  - CON: requires installing another app. If the app is already installed, why bother linking the two?
- Bundle a version of NC with Architect. Basically, include the output of npm run build as a static asset within Architect, and then open this in a new browser window.
  - PRO: Architect and Network Canvas versions are linked, so compatibility is easier to maintain. Also, better integrated. Could even force browser window attributes to, for example, emulate different devices. Example would be testing what protocol would look like on iPad while on Windows.
  - CON: How would it be integrated? Network Canvas as a submodule, and a compilation script linked to the Arc build tasks? Using the compiled bundle would mean that the preview net canvas would run in electron mode (no Cordova functionality). Might not be an issue.

**Comment by wwqrd** [comment]
Resolved by https://github.com/codaco/Architect/pull/291
