### ISSUE TITLE
Wording for Node Type

### ISSUE THREAD

**Issue by rebeccamadsen** [codaco/Architect#404]
Wording issue 1:

Sociogram, Ordinal Bin, and Categorical Bin all have this sentence in the Node Type section:

"Which node type does this name generator create?"

Should that be "interface" instead of "name generator"? Or customized to the interface?

Wording issue 2:
When editing a node type, if you try to save without a "variable", the error message refers to "prompts": "variables - You must create at least one prompt". It should say one "variable", not one "prompt".

**Comment by jthrilly** [comment]
> Should that be "interface" instead of "name generator"? Or customized to the interface?

I think just "interface" sounds good!
