### ISSUE TITLE
Changes to sociogram prompt editing

### ISSUE THREAD

**Issue by jthrilly** [codaco/Architect#416]
In order to implement #392 (variables should only be used once per interview), we need to change the way the sociogram prompt deals with layout variables and attribute highlighting.

Recap: attribute highlighting services two purposes. (1) Highlight nodes for which a given boolean variable is true. (2) Allow toggling a boolean attribute to true by tapping a node.

In order to prevent reassignment, these two purposes need to be split:

- **Highlight existing attribute**: this should allow selecting an existing Boolean variable. The variable will be for display purposes only, and will not be toggle-able.
OR
- **Create a new variable to toggle**: a modal allowing the user to type a variable name. The type (boolean) is already known and not adjustable, and there is no need for either a prompt or validation. 

Layout variables are exempt from the reassignment rule. As such, the existing drop down to select a layout variable simply needs to have an additional "create new" option added to it, which triggers a modal similar to that for the highlight variable. Once again, there is no need for a prompt, variable type, or validation to be specified, since these are already known. 

### Highlight/toggle variable
Toggle button changes input from select (from existing booleans), or text field to name a new boolean.

The toggle is to differentiate between the two behaviours: highlight (read only), or toggle (write)
![Sociogram highlight](https://user-images.githubusercontent.com/776599/54220123-96865c00-44e8-11e9-8ca0-0fb56135e2ec.png)

### Layout variable
The enhanced dropdown (`ReactSelect`) allows us to also free-type into the dropdown, this enables us to either select or create new variables with the same input:
![Layout variables](https://user-images.githubusercontent.com/776599/54220208-ccc3db80-44e8-11e9-8408-d2e1022b5caf.png)

**Comment by wwqrd** [comment]
Covers last part of: ["Portalling" to allow creating entities out of context](https://github.com/codaco/Architect/issues/360)
