### ISSUE TITLE
Is scss being properly linted?

### ISSUE THREAD

**Issue by wwqrd** [codaco/Architect#43]
Some kludges in the prototypes aren't showing scss warnings and it should.

**Comment by bryfox** [comment]
I had to make a couple of changes in Server; ymmv.

- Verbose flag is needed to see warnings; I added an [npm script](https://github.com/codaco/Server/blob/master/package.json#L21) that uses it
- Update [config file](https://github.com/codaco/Server/blob/master/.sass-lint.yml#L4) to limit linting to `src` (not, e.g., node_modules)
