### ISSUE TITLE
Some interfaces don't need to set display variable

### ISSUE THREAD

**Issue by wwqrd** [codaco/Architect#448]
Display variable can now be set as part of the NodeType section component, as a global setting. However some interfaces don't need it it, since they have things like 'card' display options.

It doesn't break anything, but may be confusing

<img width="838" alt="Screenshot 2019-04-12 at 16 16 40" src="https://user-images.githubusercontent.com/776599/56047985-755e9880-5d3e-11e9-9e07-853151c1957c.png">

**Comment by jthrilly** [comment]
Which interfaces were you thinking don't need it? If it's the name generator list interface, it uses it to determine the type of the node created by selecting a card.

**Comment by wwqrd** [comment]
Name generator list is one of them, the other is the search variant.

They both require: `prompts[n].cardOptions.displayLabel`, are you saying they need the display option to be set on variables as well?

**Comment by wwqrd** [comment]
This issue is resolved:

- Top level display label is valid, even for card based interfaces as it isn't required.
- For views with external data, this option has been removed.
