### ISSUE TITLE
Create selectors to allow selecting variables from external data sources

### ISSUE THREAD

**Issue by wwqrd** [codaco/Architect#453]
We're going to naively trust external data as is for property names. Some of these may eventually merge with properties in Network Canvas if they later turn out to exist.

For Architect this means for interfaces which reference variables on external data sources:
- variable options (i.e. for drop-downs) will be provided by scanning the external data sources
- the `protocol.json` will no longer contain variableId references for these properties, but the variable name as a string.

**Comment by jthrilly** [comment]
WIP development protocol with these changes: https://github.com/codaco/development-protocol/pull/3
