### ISSUE TITLE
Refresh insert new screen UI

### ISSUE THREAD

**Issue by wwqrd** [codaco/Architect#458]
Current "drawer" UI is a bit cumbersome and doesn't really sit well in the timeline.

We want to:
- Elevate the insert screen drawer to it's own screen
- Update the UI of the drawer to make it easier to find components
- Add a new way to insert screens (particularly relevant for new protocols, which rely on the drawer being "open" once a new protocol has been initialised)

**Comment by wwqrd** [comment]
Insert new screen treatments:
![Add bottom centre](https://user-images.githubusercontent.com/776599/56576421-3cd18100-65c0-11e9-8b61-86ca57b3c95f.png)
![Add bottom right](https://user-images.githubusercontent.com/776599/56576423-3cd18100-65c0-11e9-8515-f65c0dac86b8.png)

**Comment by wwqrd** [comment]
Insert new screen, screen:
![Insert new screen screen](https://user-images.githubusercontent.com/776599/56576485-6ee2e300-65c0-11e9-8557-5c2a2369b71e.png)

**Comment by wwqrd** [comment]
Additionally might be worth moving the top background up whilst complete this task - it shouldn't obscure the first screen.

**Comment by wwqrd** [comment]
Insert new screen with headings and accents:
![Insert new screen screen w accents](https://user-images.githubusercontent.com/776599/56577791-d51d3500-65c3-11e9-88dd-c94c81a7f030.png)

May remove the auto-highlighting.

**Comment by jthrilly** [comment]
I was thinking more like this:

![Untitled-1](https://user-images.githubusercontent.com/1387940/56578750-4d84f580-65c6-11e9-9313-2e99bbc50601.png)
