### ISSUE TITLE
Issues panel being open causes modal scrolling

### ISSUE THREAD

**Issue by jthrilly** [codaco/Architect#473]
On the sociogram edit screen, when opening the prompt configuration modal it overflows the parent window causing the need to scroll and general ugliness. 

<img width="1552" alt="Screen Shot 2019-05-07 at 3 58 25 PM" src="https://user-images.githubusercontent.com/1387940/57310021-f95b3480-70e0-11e9-9760-a4ed821ca54f.png">

**Comment by wwqrd** [comment]
Another example with deeper modals:

<img width="1552" alt="Screenshot 2019-06-10 at 17 39 43" src="https://user-images.githubusercontent.com/776599/59211158-1c2cad00-8ba7-11e9-8a79-cc782ecbb54a.png">

**Comment by wwqrd** [comment]
Resolved in #551
