### ISSUE TITLE
Removing an asset does not remove references to it

### ISSUE THREAD

**Issue by jthrilly** [codaco/Architect#475]
1 - Add an image asset
2 - Add as background image to one or more sociogram screens
3 - Remove image asset from asset manager
4 - Asset is still referenced by UID in sociogram configuration, but the editor shows concentric circles selected.

Solution: do not allow removing assets that are in use. Inform user where asset is in use when they attempt to delete.

**Comment by wwqrd** [comment]
Adding an asset through the asset manager is not a savable change either, suggest this is fixed here.

**Comment by wwqrd** [comment]
Also might be worth reviewing how unused assets are deleted from disk, to use the same code paths as the usage checker here.
