### ISSUE TITLE
Help text and general missing copy

### ISSUE THREAD

**Issue by wwqrd** [codaco/Architect#50]
We need help text and other copy throughout the app, including:

- Help text for each "section" that can be edited in an interface (For the context panel on the stage edit view)
- Introduction text for each type of interface? (At the beginning of the stage edit view)
- Short descriptions for each type of interface (For the insert interface view)

**Comment by wwqrd** [comment]
Template for required copy: [Architect copy.xlsx](https://github.com/codaco/Architect/files/2025879/Architect.copy.xlsx)

**Comment by jthrilly** [comment]
I've created this copy for you, and will add a branch that adds it shortly.

**Comment by wwqrd** [comment]
Resolved: https://github.com/codaco/Architect/pull/74
