### ISSUE TITLE
error using "0" for values

### ISSUE THREAD

**Issue by rebeccamadsen** [codaco/Architect#506]
Here are some examples of where "0" is not an accepted value in the ui, though it should be allowed.

1. Skip logic using a number variable:
![skip logic 3](https://user-images.githubusercontent.com/16093053/58972853-84852400-878c-11e9-88d5-c3f745cb70af.png)

2. Ordinal variable creation on ordinal bin (categorical bin is similar):
![ord](https://user-images.githubusercontent.com/16093053/58972911-a67ea680-878c-11e9-95f6-248524a593b7.png)

**Comment by wwqrd** [comment]
Resolved by https://github.com/codaco/Architect/pull/511
