### ISSUE TITLE
windows save issue

### ISSUE THREAD

**Issue by rebeccamadsen** [codaco/Architect#509]
On windows, I couldn't save a protocol even though it was valid. This error came up:

![save](https://user-images.githubusercontent.com/16093053/58973817-e6df2400-878e-11e9-8605-e01480f75643.png)

On looking in the temp directory, the protocol directory has no "assets" directory, though other temp protocols do have the assets directory. I have not been able to duplicate this to figure out why the assets directory is missing in this case.

**Comment by wwqrd** [comment]
Okay a couple of things I think we can do about this:
- Stop this from crashing a save, that seems overly harsh
- There was some code managing the contents of temp, could be a possible cause and is probably needless since that should be managed by the OS.

**Comment by jthrilly** [comment]
We have addressed what we can of this in this release, so I am removing the blocker label. I will keep the issue open incase if comes back longer term.

**Comment by wwqrd** [comment]
Can we close this for now? Can always be re opened if it crops up again.
