### ISSUE TITLE
require values for additionalAttributes

### ISSUE THREAD

**Issue by rebeccamadsen** [codaco/Architect#513]
Related to #264. We made additional Attributes default boolean values to true before, and it should do so again. Otherwise, no value is recorded.

Also, it is possible to create variables of other types (text, ordinal, etc) and save the prompt without assigning a value to them. Those will generate protocol validation errors when trying to save the protocol later. Can we require a value if a variable is selected on additional attributes? A variable is optional, but once a variable is there, the value should be required.

**Comment by wwqrd** [comment]
<img width="1304" alt="Screenshot 2019-06-06 at 12 21 11" src="https://user-images.githubusercontent.com/776599/59029256-b2826b00-8855-11e9-9ced-dcd1733fe2ab.png">

For categorical values do you think we should enforce at least one value to be selected?
