### ISSUE TITLE
Additional attributes doesn't require values

### ISSUE THREAD

**Issue by wwqrd** [codaco/Architect#514]
- When setting additional attributes, values aren't required.

- If they aren't provided then this attribute is not set:

  ```js
  // output
  { variable: 'foo' }
  
  // should be
  { variable: 'foo', value: ? }
  ```

- Additionally, when changing variable, value is not reset.

**Comment by wwqrd** [comment]
In attributes table, boolean inputs should use a toggle (so that they default to _false_)

**Comment by jthrilly** [comment]
duplicate of #513
