### ISSUE TITLE
add ability to remove skip logic

### ISSUE THREAD

**Issue by rebeccamadsen** [codaco/Architect#517]
If a user changes their mind about having skip logic on a stage, we should have some way to remove it without deleting the whole stage.

Once deleting skip logic is possible, it would make sense to also require existing skip logic have at least one rule, and to require "Any" or "All" to be selected.

I wonder about whether it makes sense to have an indicator either in the timeline or the stage view that a stage has skip logic on it? Right now the only indication is to click on "configure skip logic" again or to drill into the code view.

**Comment by jthrilly** [comment]
This should be addressed as part of https://github.com/codaco/Architect/issues/617
