### ISSUE TITLE
No way to edit a categorical/ordinal variable from associated interface

### ISSUE THREAD

**Issue by jthrilly** [codaco/Architect#525]
- On the ordinal/categorical interface editor, we can create an appropriate variable, along with options 👍 

- However, once created, there is no way to edit this variable or its options 👎 

- There's also no way to even view the options within the variable 👎 

We need to revise the UI here, and perhaps in other places where ordinal/categorical variables are used, to allow for editing the options after the variable is created. This shouldn't break anything, as the type will remain constant, the name will remain constant, and the input component (if defined) won't be touched.

Suggestions for a UI for this welcome. We have two goals with this specific issue: 
- Show the existing option values to the user. Perhaps an approximation of the interface, using the color scale specified (in the case of ordinal)?
- Allow editing these options.

**Comment by wwqrd** [comment]
How about we move the options editor inline?

![Options](https://user-images.githubusercontent.com/776599/60027751-f23eb480-9695-11e9-9b8d-2e0158870b06.png)

**Comment by jthrilly** [comment]
Removing options inline would be great. 

Another feature request we have had for the categorical bin is an "other" box that prompts for a value via a text box when a node is dropped into it.

Probably significant enough for it's own issue, but just wanted to mention it here.
