### ISSUE TITLE
Add new stage button is clipped at bottom, revealing timeline

### ISSUE THREAD

**Issue by wwqrd** [codaco/Architect#528]
<img width="272" alt="Screenshot 2019-06-11 at 11 08 21" src="https://user-images.githubusercontent.com/776599/59263608-4929a000-8c39-11e9-81f3-2ee95ec7455c.png">

**Comment by jthrilly** [comment]
Just wondering: is this font size specific? Could be to do with mixing relative and pixel units.

**Comment by wwqrd** [comment]
Looks to me like it only happens for the 5th screen, so I'm assuming it's a rounding issue?
