### ISSUE TITLE
Form section allows use of same variable multiple times

### ISSUE THREAD

**Issue by wwqrd** [codaco/Architect#532]
It is possible to specify the same variable for two different fields in the Form section.

Whilst this seems odd, it doesn't cause validation issues, or break network canvas (both fields are filled out simultaneously).

<img width="753" alt="Screenshot 2019-06-11 at 16 12 41" src="https://user-images.githubusercontent.com/776599/59284245-d84bad80-8c63-11e9-9e16-fdf822b8bc67.png">

**Comment by rebeccamadsen** [comment]
Related to #298?

**Comment by wwqrd** [comment]
I think the whole component might have been replaced since then, but it's definitely the same issue!
