### ISSUE TITLE
Name Generator Prompt can set layout variable in additional attributes

### ISSUE THREAD

**Issue by wwqrd** [codaco/Architect#535]
Name generator can set layout variable as an additional attribute, this field is rendered as a text input.

Either layout variable should not be assignable here, or it should render an appropriate component to edit it (should set an object with x, y attributes constrained to [-1, 1]).

<img width="1110" alt="Screenshot 2019-06-11 at 18 13 16" src="https://user-images.githubusercontent.com/776599/59292295-b0b11100-8c74-11e9-9104-a6d864a8c5ec.png">

**Comment by jthrilly** [comment]
I think it should probably be excluded from this list.
