### ISSUE TITLE
Handle opening .netcanvas files by file association

### ISSUE THREAD

**Issue by jthrilly** [codaco/Architect#55]
Pr #54 adds a file association for Architect and .netcanvas files.

We now need to handle these files within Architect. From what I can tell, the file gets passed as an argument when the app is launched, but to handle this correctly we need to ensure we are running as a single instance: https://github.com/electron/electron/issues/8006

Once that is done, we can look to `argv` to get the path to the opened file. This will then need to be passed to the renderer side, and then used to trigger the file open methods.

**Comment by wwqrd** [comment]
Working but 2 things I'd like to refine:

Animation: when not loading from the protocol stacks, the current animation doesn't make sense (is half).

When opening from scratch to load by file association, briefly shown start screen, loading would be better.
