### ISSUE TITLE
some variables show as unused incorrectly

### ISSUE THREAD

**Issue by rebeccamadsen** [codaco/Architect#590]
Some variables in the codebook show up as unused even if they are in use. This means I can delete them and then get validation errors when I attempt to save the protocol.

For example, layout variables and variables used as additional attributes.

Possibly unrelated, but "used in:" info ends up with extra commas when viewing the latest release of the Development protocol.

![vars](https://user-images.githubusercontent.com/16093053/66872261-8ac5b100-ef73-11e9-933b-317e721ac4fb.png)

**Comment by wwqrd** [comment]
Also missing from variable indexes are: 
- skipLogic
- stage filters
- narrative panels
- name generator panel filter
