### ISSUE TITLE
Remove scrollbar from "used in" table in codebook

### ISSUE THREAD

**Issue by jthrilly** [codaco/Architect#593]
The 'used in' column in the codebook includes a scrollbar when there are more than a certain number of items. We should find a way to remove it.

**Comment by jthrilly** [comment]
Ah! That makes sense. Issue stands though, as I think scrollbars in Windows need custom styling, generally.

**Comment by jthrilly** [comment]
> This is just a temporary fix to make the list usable, and should probaby be changed to not use scrollbars at all, e.g. a tooltip.

Couldn't it just wrap? Is the uniformity of the row height that important?

**Comment by wwqrd** [comment]
Yes it could wrap that's another option.

**Comment by wwqrd** [comment]
So this is using react-virtualised for the table functionality.

That gives us sorting for free, and would be great if we added search.

But it doesn't support dynamic heights for the content. The way I got around this before was to calculate the total height based on a fixed cell height and a known number of items. The drawback was that the text had to scroll.

So our options to fix this are:
- Find another way to display additional items, e.g. a tooltip
- Have dynamic cell heights using a cell measurer, but that would mean using a fixed height for the table.
- Estimate the cell heights based on text length, but that would be pretty unreliable.
- Remove the usage column, I don't think it was part of the original spec.
- Use another table library, or ditch the table library and rebuild this component.

**Comment by jthrilly** [comment]
> So our options to fix this are:
> 
>     * Find another way to display additional items, e.g. a tooltip
> 
>     * Have dynamic cell heights using a cell measurer, but that would mean using a fixed height for the table.
> 
>     * Estimate the cell heights based on text length, but that would be pretty unreliable.
> 
>     * Remove the usage column, I don't think it was part of the original spec.
> 
>     * Use another table library, or ditch the table library and rebuild this component.

Well, this is pants. 

As you say, it looks like dynamic heights are possible using the cell measurer( https://bvaughn.github.io/react-virtualized/#/components/CellMeasurer) . I don't see what the issue is with having a fixed height for the table.

**Comment by jthrilly** [comment]
If we can't fix this using the above, let's reimplement this without `react-virtualized`. Its too limiting. Sort and search are more easily added back in. If we do this, the default sort should be by variable name until we have time to add dynamic sorting.

**Comment by jthrilly** [comment]
One other thought. I'm not sure exactly what the internals of the library look like, but if the `rowHeight` property of a table can be a function that calculates the height of a row based on its index, why can't we render the item content and then get its `offsetHeight`?

**Comment by wwqrd** [comment]
As I understand the AutoSizer is for to expand to fill space, not to expand to fit content - in fact this usage really goes against the purpose of react virtualised (long lists that you don't want to render all at once). I think removing this library makes sense.
