### ISSUE TITLE
No way to delete node or edge types

### ISSUE THREAD

**Issue by jthrilly** [codaco/Architect#618]
We currently lack a way to delete entire node or edge types from the codebook management screen, or elsewhere in the app.

**Comment by wwqrd** [comment]
This is already possible, but the delete button is not shown unless the type is unused.

We could update the delete button to always be visible and show a tooltip/dialog if the user clicks on it when it's not currently possible.

**Comment by jthrilly** [comment]
Can we also add a link to the "manage codebook" screen from the entity type choose? Just a short text link that says something like "visit the [manage codebook] screen to delete unused node or edge types."
