### ISSUE TITLE
Error uploading PNG image file to asset library

### ISSUE THREAD

**Issue by katebanner** [codaco/Architect#630]
When trying to add a PNG image file to the asset library in Architect, Michelle received the following error. 
<img width="751" alt="Screen Shot 2020-05-12 at 2 45 40 PM" src="https://user-images.githubusercontent.com/25466051/81744490-e8b66a80-9468-11ea-87f7-8563e6642665.png">

Michelle was using her Mac, but Rocco also tried from his PC and received the same error. Here's the image that they tried to add. 
![NC_COVID_Background_01](https://user-images.githubusercontent.com/25466051/81744618-14395500-9469-11ea-8815-501cb16073bb.png)

**Comment by jthrilly** [comment]
I have verified this as already fixed in the master branch.
