### ISSUE TITLE
Ordinal variables aren't working with skip logic

### ISSUE THREAD

**Issue by katebanner** [codaco/Architect#632]
There is a bug preventing the use of ordinal variables in skip logic. When a rule is being defined the value section is greyed out and cannot be modified.

**Comment by katebanner** [comment]
![slopsurvey](https://user-images.githubusercontent.com/25466051/81869633-01428580-953a-11ea-8b4f-593e27b34ead.jpg)

**Comment by wwqrd** [comment]
This applies to ego rules only and also affects categorical variables.
