### ISSUE TITLE
Constrain variable names and option values

### ISSUE THREAD

**Issue by wwqrd** [codaco/Architect#645]
For interoperability variable names, and categorical/ordinal option values must be constrained. Update inputs/validation to ensure these constraints are upheld.

- Properties to respect the constraint:
  `/^[a-zA-Z0-9._\\-:]*$/`
- All node/edge/ego **variable names**
- All categorical/ordinal **options values**

**Comment by jthrilly** [comment]
Migration should also include rich information for the user, including the ability to link to a documentation article.
