### ISSUE TITLE
Opening .netcanvas files behaves inconsistently across platforms

### ISSUE THREAD

**Issue by wwqrd** [codaco/Architect#65]
Currently:

OSX:
Single window, when opening a file, currently opened file is "closed"

Windows:
Multiple windows, can open the same .netcanvas file in multiple windows simultaneously.

Proposed behaviour (both platforms):

When opening different .netcanvas files, open new windows, when opening the same .netcanvas file, focus window.

**Comment by wwqrd** [comment]
Partly fixed, in that both platforms now act like OS X. Plan to revisit this.

**Comment by wwqrd** [comment]
@jthrilly What's the intended behaviour for this?

**Comment by jthrilly** [comment]
I think just something "deliberate". Having the app be single window is fine, but to finish this feature off we should check for things like "closing the current file (to open a new one) would cause data loss". If that's not an issue, I'm happy with how it is working now.

**Comment by wwqrd** [comment]
I think given that we have a home screen that allows the user to switch between protocols from within the app - the simplest thing to do right now is keep this as a single window application.

So for this task I think the resolution is:
- Fix the multiple window shortcut from #164 
- Introduce a prompt to save when application is about to switch protocols.
