### ISSUE TITLE
Quick add variables are not recognised in the "used-in" section of the codebook

### ISSUE THREAD

**Issue by jthrilly** [codaco/Architect#654]
As per the title, variables used in the "quick add" version of the name generator are not recognized as being in use in the codebook:

<img width="1552" alt="Screen Shot 2020-06-30 at 12 35 49 PM" src="https://user-images.githubusercontent.com/1387940/86121632-3d23b100-bace-11ea-8426-c16cc498d029.png">
<img width="1552" alt="Screen Shot 2020-06-30 at 12 36 02 PM" src="https://user-images.githubusercontent.com/1387940/86121641-444abf00-bace-11ea-95ed-63005d452ee5.png">

**Comment by rebeccamadsen** [comment]
I'm not seeing this; quick add variables show as used for me in the codebook.

**Comment by jthrilly** [comment]
<img width="1552" alt="Screen Shot 2020-07-31 at 10 17 06 AM" src="https://user-images.githubusercontent.com/1387940/89020547-fe745700-d316-11ea-9b77-6dd03b9286a7.png">

Definitely there for me (above is single stage new protocol).

Protocol file for testing:

[quick add.netcanvas.zip](https://github.com/codaco/Architect/files/5006176/quick.add.netcanvas.zip)

**Comment by jthrilly** [comment]
Checked again, and this is fixed in master. Was an issue in 5.2.0 interim build.
