### ISSUE TITLE
Asset modal z-index

### ISSUE THREAD

**Issue by wwqrd** [codaco/Architect#658]
Asset modal is not showing up when attempting to select an asset on the information screen.

Looks like a z-index issue.

**Comment by jthrilly** [comment]
I had this same issue, and thought I resolved it here: https://github.com/codaco/Architect/pull/651/commits/43badc4db6d191f4a347f0e1d6a681b2b3c9a960

Can you confirm it isn't resolved now that PR is in?

**Comment by jthrilly** [comment]
Also, please remember to assign project and milestone on new issues!

**Comment by rebeccamadsen** [comment]
I'm not seeing this. The information stage, add new asset, right?

**Comment by jthrilly** [comment]
As I thought, this is resolved.
