### ISSUE TITLE
Ability to embed html in help/description text

### ISSUE THREAD

**Issue by jthrilly** [codaco/Architect#71]
The help/description text is often stored as simple strings with an object. It would be great to have the ability to add formatting. Some considerations

- I primarily want to be able to insert paragraph breaks, so that I can spread out the pacing of complicated information.
- The ability to use bold and italic text would also be useful in this regard
- At some point, we might want to be able to translate these UI strings, so keeping them in separate objects, and ideally with the text separate from the markup, is not a bad thing.
- These use cases seem to lend themselves well to perhaps using markdown again, although since these strings are embedded within the app there is little danger of malicious code injection, so we could just directly `render()` the value of the strings, allowing them to be written in JSX.

**Comment by wwqrd** [comment]
That's an interesting thought about translations.

Using markdown seems like a good idea for handling the formatting of lots of different translation files.

My inclination would be to make the changes to the structure when we implement translations. Though if we have a library or architecture in mind, we could ensure we make it easier to swap in later.

**Comment by wwqrd** [comment]
Is this resolved? Think it might be worth making a separate issue for translations?

**Comment by jthrilly** [comment]
We do have it, but it is pushed to near release. I'll close this for now.
