### ISSUE TITLE
New screen cards do not match descriptions

### ISSUE THREAD

**Issue by jthrilly** [codaco/Architect#79]
The preview cards don't match the description text. See screenshot.

<img width="1611" alt="screen shot 2018-05-31 at 3 10 32 pm" src="https://user-images.githubusercontent.com/1387940/40787170-d8d798ba-64e4-11e8-8181-7b65d55d4ade.png">

**Comment by wwqrd** [comment]
This is going to be related to sorting (RHS is using unsorted indexes), might be worth adding ids.
