### ISSUE TITLE
Add content buttons aligned badly, especially on narrower layouts

### ISSUE THREAD

**Issue by wwqrd** [codaco/Architect#83]
<img width="1392" alt="screen shot 2018-05-31 at 16 07 12" src="https://user-images.githubusercontent.com/776599/40790464-eb0deae0-64ec-11e8-9696-8f8ab94693b3.png">

**Comment by wwqrd** [comment]
Is this fixed by #122 ?

**Comment by jthrilly** [comment]
Yup!
