### ISSUE TITLE
Should titles have a character limit or be displayed with ellipsis? What about other content types?

### ISSUE THREAD

**Issue by wwqrd** [codaco/Architect#84]
<img width="1524" alt="screen shot 2018-05-31 at 16 09 46" src="https://user-images.githubusercontent.com/776599/40790525-1be29d6e-64ed-11e8-806b-9be13f984628.png">

**Comment by wwqrd** [comment]
Also, there are other places which might benefit from these kinds of limits:

<img width="1512" alt="screen shot 2018-05-31 at 16 11 27" src="https://user-images.githubusercontent.com/776599/40790632-5f3969b2-64ed-11e8-8da5-1e622033b525.png">

**Comment by jthrilly** [comment]
The title should be constrained to a char limit. Let's start with 12 and see how we go.
