### ISSUE TITLE
Screens can't be reordered in the Timeline view

### ISSUE THREAD

**Issue by wwqrd** [codaco/Architect#86]

**Comment by wwqrd** [comment]
Looking at implementing this and unsure how to proceed with the alternating rows:

<img width="718" alt="screen shot 2018-09-04 at 18 20 35" src="https://user-images.githubusercontent.com/776599/45046827-4036ed00-b06f-11e8-839f-a05ba05d827c.png">

I think what will happen without intervention is that when a screen is dropped, all screens will flip to their correct odd/even positions instantly - which could be a whole lot of them.

One approach would be to try and animate that change, but that might look kind of odd? Is this design likely to change? If so, maybe this is a good time to do it?

**Comment by wwqrd** [comment]
@jthrilly pinging for your thoughts

**Comment by jthrilly** [comment]
Tricky! The alternating sides creates an issue for us here that I didn't anticipate. I'm afraid I don't have any good solutions for making it look good. I think as long as the dragging UI is intuitive (i.e the user has as clear an idea as possible of what is being dragged, and where it will end up) then the timeline updating instantly shouldn't be too big of an issue.
