### ISSUE TITLE
It's possible to create a name generator interface with no prompts.

### ISSUE THREAD

**Issue by wwqrd** [codaco/Architect#89]
We can create technically invalid protocols, such as a prompt-less name generator. Since this could be a work in progress, I'm not sure we should disallow it, however it might be worth thinking about some kind of "issues" notification/view.

**Comment by jthrilly** [comment]
I think this can be closed, given we've talked about protocol validation in a bit more depth now. @wwqrd?

**Comment by wwqrd** [comment]
I see what we've talked about so far more along the lines of field-level validation, and using json schema as part of that and/or automated testing (i.e. does architect create protocols that match the spec generally).

This question here is more like a "compete your protocol" type prompt:
> "You have one name generator without any prompts [click here to edit stage]"

**Comment by jthrilly** [comment]
Ah, I see.

In this case, prompts.length > 0 is a requirement of creating this stage, as you point out. Is that going to be a problem to implement with how you are currently doing validation?

**Comment by wwqrd** [comment]
Just to update with the conversation on slack:

It shouldn't be possible to "save" a invalid stage in architect, i.e. we don't allow work in progress interfaces in the first place.
