### ISSUE TITLE
Inconsistent icons on the logic editor

### ISSUE THREAD

**Issue by wwqrd** [codaco/Architect#90]
<img width="841" alt="screen shot 2018-05-31 at 16 39 42" src="https://user-images.githubusercontent.com/776599/40792279-7f10a3fa-64f1-11e8-9548-304c08feade7.png">

I believe the design of the logic editor could change, so possibly one for later.

**Comment by wwqrd** [comment]
Relates to #91

**Comment by jthrilly** [comment]
Could also form part of https://github.com/codaco/Network-Canvas-UI/issues/64

Either way, I would like to see implementation in UI, so that these can be reused.

**Comment by wwqrd** [comment]
This is partially fixed for prompts, with icons being added to UI - the filter editor is likely to have more style changes in the future, so closing this issue for now.
